---
- name: Testing andrewrothstein.rke
  hosts: all
  tasks:
    - name: Installing andrewrothstein.rke
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Executing 'rke --version'
      ansible.builtin.command: /usr/local/bin/rke --version
      changed_when: false
      register: rke_test_output
    - name: Output from 'rke --version'
      ansible.builtin.debug:
        msg: '{{ rke_test_output.stdout }}'
